spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bkdata?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    # jdbc:mysql://211.71.15.42:3306/bkdata?useSSL=false
    username: root
    password: 12345
    # g304g304
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 300s
  session:
    timeout: 5000s
  cache:
    type: redis
  activemq:
    packages:
      trust-all: true

server:
  port: 8081
  connection-timeout: 5000s
  servlet:
    session:
      timeout: 5000s

mybatis:
  mapper-locations: classpath:GreatMapper.xml
  config-location: classpath:mybatis.xml
