spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.71.15.42:3306/bkdata?useSSL=false
    username: root
    password: g304g304

  redis:
    host: 192.168.48.1
    port: 6379
    timeout: 300s
  session:
    timeout: 5000s

server:
  port: 8081
  connection-timeout: 5000s
  servlet:
    session:
      timeout: 5000s

mybatis:
  mapper-locations: classpath:GreatMapper.xml
  config-location: classpath:mybatis.xml
